using System;

namespace RussionRoulette
{
    public class ClassGame
    {
        public ClassGame()
        {
            NewGame();
        }


        //   Random number generator
        private Random NumGenerator { get; } = new Random(DateTime.Now.Millisecond);

        //   The number of away shots available
        public int AwayCount { set; get; } = 2;

        //   The total number of chambers used game
        public int NoOfChamber { set; get; } = 6;

        //
        public int CurrentChamberID { private set; get; }

        // Total number of games player has played
        public int TotalGamePlayed { private set; get; }

        // The chamber number the bullet is in.
        //This is generated by the random generator whenever new game start.
        public int SecretChamberID { private set; get; }

        public int Win { private set; get; }

        public int Lose => TotalGamePlayed - Win;

        //   The function is called when starting a new game.
        //    generates new secret chamber ID and reset game variable to initial value;

        public void NewGame()
        {
            // generate the secret chamber ID where bullet will be
            SecretChamberID = NumGenerator.Next(1, NoOfChamber + 1);
            AwayCount = 2; // Total Available away shots 2 
            CurrentChamberID = 1; //always start on chamber 1
        }

        //   Check whether current chamber ID match the secret chamber ID.
        //  Return true if matched, else return false.
        public bool bulletShot()
        {
            return CurrentChamberID == SecretChamberID;
        }


        //   increment to the next chamber number.
        public void Next()
        {
            CurrentChamberID++;
        }

        public void YouWon()
        {
            Win++;
            TotalGamePlayed++;
        }

        public void YouLose()
        {
            TotalGamePlayed++;
        }
    }
}